update

diff --git a/build/COPY_ROOT_0/etc/services.d/turbovnc/params b/build/COPY_ROOT_0/etc/services.d/turbovnc/params
--- a/build/COPY_ROOT_0/etc/services.d/turbovnc/params
+++ b/build/COPY_ROOT_0/etc/services.d/turbovnc/params
@@ -1,10 +1,10 @@
 #!/bin/bash
 
+set -e # Exit immediately if a command exits with a non-zero status.
 set -u # Treat unset variables as an error.
 
 source /opt/ai-dock/etc/environment.sh
 
-echo "${DISPLAY}"
 echo "-geometry ${DISPLAY_SIZEW}x${DISPLAY_SIZEH}"
 echo "-depth ${DISPLAY_CDEPTH}"
 echo "-auth ~/.vnc/passwd"
