update

diff --git a/build/COPY_ROOT_0/etc/services.d/turbovnc/run b/build/COPY_ROOT_0/etc/services.d/turbovnc/run
--- a/build/COPY_ROOT_0/etc/services.d/turbovnc/run
+++ b/build/COPY_ROOT_0/etc/services.d/turbovnc/run
@@ -1,8 +1,7 @@
 #!/bin/sh
 
+set -e # Exit immediately if a command exits with a non-zero status.
 set -u # Treat unset variables as an error.
-
-#sudo rm -f /opt/TurboVNC/bin/xstartup.turbovnc
 
 sudo rm -rf /tmp/.X* ~/.cache
 
@@ -15,10 +14,4 @@ mkdir -p ~/.vnc/ ~/.dosbox
 echo $USER_PASSWORD | /opt/TurboVNC/bin/vncpasswd -f > ~/.vnc/passwd
 chmod 0600 ~/.vnc/passwd
 
-exec /opt/TurboVNC/bin/vncserver ${DISPLAY} \
-   -geometry ${DISPLAY_SIZEW}x${DISPLAY_SIZEH} \
-   -depth ${DISPLAY_CDEPTH} \
-   -auth ~/.vnc/passwd \
-   -x509key /opt/caddy/tls/container.key \
-   -x509cert /opt/caddy/tls/container.crt \
-   -vgl
+exec /opt/TurboVNC/bin/vncserver "$@"
